# Generated by Django 5.1.3 on 2025-11-23 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_participant_options_alter_tournament_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='match',
            name='contestant_b',
        ),
        migrations.RemoveField(
            model_name='match',
            name='contestant_a',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_number', 'index_in_round']},
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='number_of_rounds',
            new_name='current_round',
        ),
        migrations.RemoveField(
            model_name='match',
            name='votes_a',
        ),
        migrations.RemoveField(
            model_name='match',
            name='votes_b',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='contestant_a_name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='contestant_b_name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='voting_duration_minutes',
        ),
        migrations.AddField(
            model_name='match',
            name='index_in_round',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bracket_size',
            field=models.PositiveIntegerField(choices=[(2, '2'), (4, '4'), (8, '8'), (16, '16')], default=4),
        ),
        migrations.AddField(
            model_name='tournament',
            name='voting_duration_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('finished', 'Finished')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_thumbnails/'),
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='competitors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='competitor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_competitor1', to='tournaments.competitor'),
        ),
        migrations.AddField(
            model_name='match',
            name='competitor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_competitor2', to='tournaments.competitor'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='tournaments.competitor'),
        ),
        migrations.CreateModel(
            name='MatchVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('1', 'Competitor 1'), ('2', 'Competitor 2')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tournaments.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='TournamentImage',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
