# Generated by Django 5.1.3 on 2025-12-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_remove_participant_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Match duration in seconds (Kahoot-style countdown)'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
