# Generated by Django 5.1.3 on 2025-12-09 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_match_duration_seconds_match_match_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='pin_code',
            field=models.CharField(blank=True, help_text='6-digit PIN for participants to join', max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the tournament was started (went live)', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waiting', 'Waiting Lobby'), ('live', 'Live'), ('finished', 'Finished')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='voting_duration_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Display name for anonymous users', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
                ('user', models.ForeignKey(blank=True, help_text='Registered user (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
