# Generated by Django 5.1.3 on 2025-12-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_matchcomment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='participant',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=40, null=True),
        ),
    ]
