# Generated by Django 5.2.8 on 2025-12-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tag_tournament_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='match',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_started_at',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('finished', 'Finished')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='voting_duration_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.DeleteModel(
            name='MatchComment',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
