# Generated by Django 5.1.3 on 2025-12-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_alter_report_target_match_comment'),
        ('tournaments', '0013_match_duration_seconds_match_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='match',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('gaming', 'Gaming'), ('sports', 'Sports'), ('music', 'Music'), ('movies', 'Movies'), ('anime', 'Anime'), ('food', 'Food'), ('fashion', 'Fashion'), ('tech', 'Technology'), ('art', 'Art & Design'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.DeleteModel(
            name='MatchComment',
        ),
    ]
