# Generated by Django 5.2.9 on 2026-01-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_tournament_pin_code_alter_tournament_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
