# Generated by Django 5.2.10 on 2026-02-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_match_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='language',
            field=models.CharField(choices=[('th', 'Thai'), ('en', 'English'), ('jp', 'Japanese'), ('cn', 'Chinese'), ('kr', 'Korean'), ('other', 'Other')], default='th', max_length=10),
        ),
    ]
