# Generated by Django 5.2.10 on 2026-02-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_alter_tournament_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='language',
            field=models.CharField(choices=[('th', 'Thai'), ('en', 'English'), ('all', 'Universal / Global')], default='th', max_length=10),
        ),
    ]
