# Generated by Django 5.1.3 on 2025-12-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
        ('tournaments', '0013_match_duration_seconds_match_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_match_comment',
            field=models.ForeignKey(blank=True, help_text='Report a specific chat message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='tournaments.comment'),
        ),
    ]
