# Generated by Django 5.2.8 on 2026-01-15 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_alter_report_target_match_comment'),
        ('tournaments', '0016_match_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='target_tournament_comment',
            field=models.ForeignKey(blank=True, help_text='Report a tournament discussion comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='tournaments.comment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_match_comment',
            field=models.ForeignKey(blank=True, help_text='Report a live match chat message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='tournaments.matchcomment'),
        ),
    ]
