# Generated by Django 5.2.10 on 2026-02-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_report_target_tournament_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportTicket',
        ),
    ]
